FROM oracle/graalvm-ce:19.3.0.2-java8
CMD gu install native-image
echo $(native-image --version)
echo "Building graal native image"
sh compile.sh
echo "native image generated!"
ls -ltra target/sb-jafu-app