FROM oracle/graalvm-ce:19.3.0.2-java8
RUN gu install native-image
RUN echo $(native-image --version)
RUN echo "moving $PWD to temp"
RUN mkdir /tmp/sb-jafu-app/
COPY . /tmp/sb-jafu-app
WORKDIR /tmp/sb-jafu-app/
RUN echo "Building graal native image"
RUN sh compile.sh
RUN echo "native image generated!"
RUN ls -ltra target/sb-jafu-app